#!python
"""Top level script which runs fate."""

import os
import sys

libs_path = os.path.dirname(os.path.abspath(__file__)) + '/libs/'
sys.path.insert(0, libs_path)


import src.main

src.main.main()

